name: Run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          api_key: ${{ secrets.API_KEY }}
          api_token: ${{ secrets.API_TOKEN }}
          python-version: '3.8'
      - run: pip install -r requirements.txt
      - run: pytest
